import 'package:flutter/material.dart';
import 'package:aftercode0/screens/home/composant/framewidget/EllipseWidget.dart';
import 'NameWidget.dart';


/* Frame Component
    Autogenerated by FlutLab FTF Generator
  */
class ComponentWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 139.0,
      height: 28.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 36.0,
              top: 5.0,
              right: null,
              bottom: null,
              width: 95.0,
              height: 17.0,
              child: NameWidget(),
            ),

            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 28.0,
              height: 28.0,
              child: EllipseWidget(),
            )
          ]),
    );
  }
}
