import 'package:flutter/material.dart';

/* Rectangle Rectangle 2.9
    Autogenerated by FlutLab FTF Generator
  */
class FrameRecWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.brown,
      width: 343.0,
      height: 343.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "_",
          color: null,
          fit: BoxFit.cover,
          width: 343.0,
          height: 343.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
