import 'package:flutter/material.dart';

/* Rectangle Rectangle 2.8
    Autogenerated by FlutLab FTF Generator
  */
class FrameRecWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Visibility(
      visible: true,
      child: Container(
        width: 343.0,
        height: 343.0,
        color: Colors.red,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Image.asset(
            "_",
            color: null,
            fit: BoxFit.cover,
            width: 343.0,
            height: 343.0,
            colorBlendMode: BlendMode.dstATop,
          ),
        ),
      ),
    );
  }
}
